---
- name: Desactivar configuraciones SSH antiguas
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '^(PermitRootLogin|PasswordAuthentication|PubkeyAuthentication|AllowUsers).*'
    replace: '# \1 disabled by Ansible'
  notify:
    - Reiniciar SSH

- name: Configurar SSH hardening
  ansible.builtin.template:
    src: hardening.conf.j2
    dest: /etc/ssh/sshd_config.d/99-hardening.conf
    owner: root
    group: root
    mode: '0600'
  notify:
    - Reiniciar SSH
